Repository kolide/launcher, pull requests merged in 2018-07, with the labels that each got.

#318 Add document explaining API extension for writable capabilities
  docs/architecture/2018-07-06-control-server-api.md
Labels: Documentation, Needs: Review

#315 update osquery-go
  Gopkg.lock
Labels: Approved

#329 Add actors for individual components of launcher
  Gopkg.lock
  Gopkg.toml
  cmd/launcher/control.go
  cmd/launcher/enable.go
  cmd/launcher/extension.go
  cmd/launcher/main.go
  cmd/launcher/updater.go
Labels: Needs: Review
