Repository kolide/launcher, pull requests merged in 2024-11, with the labels that each got.

#1951 upgrade watchdog service to scheduled task
  cmd/launcher/launcher.go
  cmd/launcher/main.go
  docs/architecture/launcher_watchdog.md
  ee/powereventwatcher/power_event_watcher_windows.go
  ee/uninstall/uninstall_windows.go
  ee/watchdog/controller_other.go
  ee/watchdog/controller_windows.go
  ee/watchdog/controller_windows_test.go
  ee/watchdog/watchdog_service_windows.go
  ee/watchdog/watchdog_task_other.go
  ee/watchdog/watchdog_task_windows.go
  pkg/launcher/paths.go
  pkg/launcher/pkg_utils_windows.go
  pkg/launcher/pkg_utils_windows_test.go
Labels: features-improvements

#1953 add numeric install version value to windows registry on install
  go.mod
  go.sum
  pkg/packagekit/assets/main.wxs
  pkg/packagekit/package.go
  pkg/packagekit/package_wix.go
Labels: component:build&packaging

#1955 Set Access-Control-Allow-Credentials: true in localserver
  ee/localserver/server.go
Labels: bug-fixes

#1958 Give launcher interactive enough time to run during doctor
  ee/debug/checkups/checkups.go
  ee/debug/checkups/osquery.go
Labels: bug-fixes

#1960 Set SystemDrive env var on osquery command
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/osqueryinstance_windows_test.go
Labels: bug-fixes

#1961 Set all env vars on osquery process
  pkg/osquery/runtime/osqueryinstance.go
Labels: bug-fixes

#1963 [KATC] Add support for doubles to indexeddb parsing
  ee/indexeddb/values.go
  ee/katc/test_data/README.md
  ee/katc/test_data/indexeddbs/file__0.indexeddb.leveldb.zip
  ee/katc/test_data/main.js
Labels: component:table, bug-fixes

#1962 deny default write permissions from windows root directory
  cmd/launcher/svc_config_windows.go
  cmd/launcher/svc_config_windows_test.go
Labels: bug-fixes

#1968 Set config on interactive command in osquery checkup
  ee/debug/checkups/osquery.go
Labels: bug-fixes

#1970 Add Windows-friendly alternative for our checkup status emojis
  ee/debug/checkups/checkups.go
  ee/debug/checkups/checkups_other.go
  ee/debug/checkups/checkups_windows.go
Labels: bug-fixes

#1971 fix InstalledVersionNum for windows build
  go.mod
  go.sum
  pkg/packagekit/package_wix.go
Labels: bug-fixes
