Repository kolide/launcher, pull requests merged in 2024-09, with the labels that each got.

#1835 Restart desktop process on systray errors
  ee/agent/flags/flag_controller.go
  ee/agent/flags/keys/keys.go
  ee/agent/types/flags.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
  ee/desktop/runner/runner.go
  ee/desktop/runner/runner_darwin.go
  ee/desktop/runner/runner_linux.go
  ee/desktop/runner/runner_test.go
  ee/desktop/runner/runner_windows.go
Labels: bug-fixes

#1851 Only set arch on bin dir when we are building for Windows
  pkg/packaging/detectLauncherVersion.go
  pkg/packaging/detectLauncherVersion_test.go
  pkg/packaging/fetch.go
  pkg/packaging/packaging.go
  pkg/packaging/packaging_test.go
Labels: component:build&packaging

#1855 Check for systray error: unable to init instance: Unspecified error
  ee/desktop/runner/runner_windows.go
Labels: bug-fixes

#1868 Add coredump checkup for flare/doctor using coredumpctl only
  ee/allowedcmd/cmd_linux.go
  ee/debug/checkups/checkups.go
  ee/debug/checkups/coredump_linux.go
  ee/debug/checkups/coredump_other.go
Labels: features-improvements

#1869 Set slogger on rungroup after logshipping is set up, so that rungroup logs will be shipped
  cmd/launcher/desktop.go
  cmd/launcher/launcher.go
  ee/watchdog/watchdog_service_windows.go
  pkg/rungroup/rungroup.go
  pkg/rungroup/rungroup_test.go
Labels: bug-fixes

#1873 batch tmutil call args to prevent argument list too long errors
  ee/agent/timemachine/timemachine_darwin.go
Labels: bug-fixes

#1872 Custom error for homebrew table not found
  ee/allowedcmd/cmd.go
  ee/tables/homebrew/upgradeable.go
Labels: component:table
