Repository kolide/launcher, pull requests merged in 2024-10, with the labels that each got.

#1887 allow update during initial delay when overridding initial delay
  ee/tuf/autoupdate.go
Labels: bug-fixes

#1890 Perform presence detection on Windows using UserConsentVerifier interop
  ee/presencedetection/presencedetection.go
  ee/presencedetection/presencedetection_linux.go
  ee/presencedetection/presencedetection_windows.go
  go.mod
  go.sum
Labels: features-improvements

#1895 Remove macos-12 runner since it will be deprecated soon
  .github/workflows/go.yml
  pkg/make/builder.go
Labels: component:build&packaging

#1901 Set osquery version in packaging context
  pkg/packagekit/context.go
  pkg/packagekit/context_test.go
  pkg/packagekit/package_fpm.go
  pkg/packagekit/package_pkg.go
  pkg/packagekit/package_wix.go
  pkg/packaging/helpers.go
  pkg/packaging/packaging.go
Labels: component:build&packaging

#1926 Remove mixer/clock due to bug
  go.mod
  go.sum
  pkg/osquery/extension.go
  pkg/osquery/extension_test.go
Labels: bug-fixes
