Repository kolide/launcher, pull requests merged in 2025-05, with the labels that each got.

#2236 Add counter to track tablewrapper timeouts
  ee/observability/meter.go
  ee/tables/tablewrapper/tablewrapper.go
Labels: features-improvements

#2237 Make cached query results TTL cloud-configurable
  ee/agent/flags/flag_controller.go
  ee/agent/flags/keys/keys.go
  ee/agent/types/flags.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
  ee/tables/windowsupdatetable/windowsupdate_cached.go
Labels: features-improvements

#2238 Record tablewrapper generate timeouts in span
  ee/tables/tablewrapper/tablewrapper.go
Labels: features-improvements

#2240 Kick off cache attempt when exiting modern standby
  cmd/launcher/launcher.go
  ee/tables/windowsupdatetable/cache_other.go
  ee/tables/windowsupdatetable/cache_test.go
  ee/tables/windowsupdatetable/cache_windows.go
  ee/tables/windowsupdatetable/windowsupdate.go
Labels: features-improvements

#2241 Ensure windows_updates_cacher logs are shipped to cloud
  cmd/launcher/launcher.go
Labels: bug-fixes

#2243 Increase buffer size to prevent deadlock on sending to channel
  ee/tuf/autoupdate.go
Labels: bug-fixes

#2244 Part 1 of removing AutoupdateErrorsStore
  ee/tuf/autoupdate.go
  ee/tuf/autoupdate_test.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/runtime_test.go
  pkg/osquery/table/table.go
Labels: bug-fixes

#2252 Track checkups "score" and error count as metrics
  ee/debug/checkups/checkpoint.go
  ee/observability/meter.go
  ee/observability/meter_test.go
Labels: features-improvements

#2254 Update KATC test databases
  ee/katc/test_data/indexeddbs/1985929987lbadutnscehter.sqlite.zip
  ee/katc/test_data/indexeddbs/file__0.indexeddb.leveldb.zip
  ee/katc/test_data/main.js
Labels: tests-docs

#2262 Store registrations in new registration store
  ee/agent/knapsack/knapsack.go
  ee/agent/storage/bbolt/stores_bbolt.go
  ee/agent/storage/ci/stores_ci.go
  ee/agent/storage/stores.go
  ee/agent/types/mocks/knapsack.go
  ee/agent/types/registration.go
  ee/agent/types/stores.go
  ee/debug/checkups/enroll-secret.go
  pkg/osquery/extension.go
  pkg/osquery/extension_test.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/runtime_test.go
Labels: features-improvements

#2264 Get munemo for header checks from registration store
  ee/localserver/dt4a_test.go
  ee/localserver/krypto-ec-middleware.go
  ee/localserver/krypto-ec-middleware_test.go
  ee/localserver/request-controlservice_test.go
  ee/localserver/request-id_test.go
  ee/localserver/request-query_test.go
  ee/localserver/server.go
  ee/localserver/server_test.go
Labels: features-improvements

#2266 Add Dependency Updates section to release.yml
  .github/release.yml
Labels: tests-docs

#2263 Get munemo from registration store when performing db reset check
  ee/agent/reset.go
  ee/agent/reset_test.go
  ee/uninstall/uninstall.go
Labels: features-improvements

#2265 Upgrade to modernc.org/sqlite@v1.37.1 to fix data races in tests
  go.mod
  go.sum
Labels: dependencies

#2267 Print logs and interrupt start time when interrupt test fails
  cmd/launcher/signal_listener_test.go
  ee/agent/storage/bbolt/backup_test.go
  ee/control/actionqueue/actionqueue_test.go
  ee/control/consumers/remoterestartconsumer/remoterestartconsumer_test.go
  ee/control/control_test.go
  ee/debug/checkups/checkpoint_test.go
  ee/desktop/runner/runner_test.go
  ee/desktop/user/universallink/handler_other_test.go
  ee/localserver/server_test.go
  ee/observability/exporter/exporter_test.go
  ee/powereventwatcher/power_event_watcher_other_test.go
  ee/secureenclaverunner/secureenclaverunner_test.go
  ee/tables/windowsupdatetable/cache_test.go
  ee/tpmrunner/tpmrunner_test.go
  ee/tuf/autoupdate_test.go
  ee/watchdog/controller_windows_test.go
  pkg/log/logshipper/logshipper_test.go
Labels: tests-docs

#2269 Add histogram meter to track RSS in bytes for launcher process
  ee/observability/meter.go
  ee/observability/meter_test.go
  ee/performance/stats.go
Labels: features-improvements

#2268 Handle near-simultaneous calls to Interrupt in secureenclaverunner
  cmd/launcher/signal_listener.go
  ee/agent/storage/bbolt/backup.go
  ee/control/consumers/remoterestartconsumer/remoterestartconsumer.go
  ee/debug/checkups/checkpoint.go
  ee/desktop/runner/runner.go
  ee/desktop/user/notify/notify_darwin.go
  ee/desktop/user/notify/notify_linux.go
  ee/desktop/user/notify/notify_windows.go
  ee/desktop/user/universallink/handler_darwin.go
  ee/desktop/user/universallink/handler_other.go
  ee/observability/exporter/exporter.go
  ee/powereventwatcher/power_event_watcher_other.go
  ee/powereventwatcher/power_event_watcher_windows.go
  ee/secureenclaverunner/secureenclaverunner.go
  ee/tables/windowsupdatetable/cache_other.go
  ee/tables/windowsupdatetable/cache_windows.go
  ee/tpmrunner/tpmrunner.go
  ee/tuf/autoupdate.go
  ee/watchdog/controller_windows.go
  pkg/osquery/extension.go
  pkg/osquery/runtime/runner.go
Labels: features-improvements

#2272 Fix potential panic during osquery instance shutdown
  pkg/osquery/runtime/osqueryinstance.go
Labels: bug-fixes

#2273 New Table! The deadly sleeper
  ee/tables/sleeper/table.go
  pkg/osquery/table/table.go
Labels: component:table

#2274 Add callback queue to localserver
  ee/localserver/krypto-ec-middleware.go
  ee/localserver/krypto-ec-middleware_test.go
  ee/localserver/server.go
  ee/localserver/server_test.go
Labels: features-improvements

#2275 prevent comshim panics
  cmd/launcher/query_windowsupdates_windows.go
  ee/tables/windowsupdatetable/windowsupdate.go
  ee/watchdog/controller_windows.go
  ee/wmi/wmi.go
  go.mod
  go.sum
Labels: bug-fixes

#2276 add launchd logs to flares
  ee/debug/checkups/checkups.go
  ee/debug/checkups/launchd_darwin.go
  ee/debug/checkups/launchd_other.go
Labels: features-improvements

#2277 Gather performance stats for launcher child processes
  ee/debug/checkups/performance.go
  ee/observability/exporter/exporter.go
  ee/observability/meter.go
  ee/observability/meter_test.go
  ee/performance/stats.go
Labels: features-improvements

#2284 Run system time checkup in log checkpointer
  ee/debug/checkups/checkups.go
Labels: observability
