Repository kolide/launcher, pull requests merged in 2025-06, with the labels that each got.

#2287 Account for identifer in binary directory and services checkups
  ee/debug/checkups/binary_directory.go
  ee/debug/checkups/checkups.go
  ee/debug/checkups/services_other.go
  ee/debug/checkups/services_windows.go
Labels: bug-fixes

#2290 Skip ending spans for nil spans; log nil spans
  cmd/launcher/launcher.go
  ee/observability/bufspanprocessor/bufspanprocessor.go
  ee/observability/bufspanprocessor/bufspanprocessor_test.go
  ee/observability/exporter/exporter.go
  ee/observability/exporter/exporter_test.go
  ee/observability/exporter/initial_trace_buffer.go
Labels: bug-fixes

#2293 Require machine GUID change when detecting hardware change on Windows
  ee/agent/reset.go
  ee/agent/reset_test.go
Labels: features-improvements

#2296 remove extra DB creations in extension tests
  pkg/osquery/extension_test.go
  pkg/osquery/log_publication_state_test.go
Labels: tests-docs

#2299 Remove windows-2019 in preparation for deprecation; add windows-2025
  .github/workflows/go.yml
Labels: tests-docs

#2300 Check that index was found before using it to access slice
  ee/tables/execparsers/dnf/parser.go
  ee/tables/execparsers/dnf/parser_test.go
Labels: bug-fixes

#2303 Fix control service Fetch deadlock (hopefully)
  ee/agent/flags/flag_controller.go
  ee/agent/flags/flag_controller_test.go
Labels: bug-fixes

#2305 Upgrade some log levels to LevelReportedError
  cmd/launcher/launcher.go
  ee/control/client_http.go
  ee/control/consumers/flareconsumer/flareconsumer.go
  ee/localserver/server.go
  ee/observability/bufspanprocessor/bufspanprocessor.go
  ee/tables/windowsupdatetable/cache_windows.go
  pkg/osquery/runtime/runner.go
Labels: observability

#2306 Add additional attributes to traces and metrics
  ee/observability/exporter/exporter.go
  ee/observability/exporter/exporter_test.go
Labels: observability

#2297 Add ResetOnHardwareChangeEnabled feature flag; reset the db if change is detected and flag is enabled
  cmd/launcher/launcher.go
  cmd/launcher/main.go
  ee/agent/flags/flag_controller.go
  ee/agent/flags/keys/keys.go
  ee/agent/reset.go
  ee/agent/reset_test.go
  ee/agent/types/flags.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
Labels: features-improvements

#2311 Downgrade some log levels from error to warn
  ee/control/control.go
  ee/secureenclaverunner/secureenclaverunner.go
  pkg/service/middleware.go
  pkg/service/publish_logs.go
  pkg/service/publish_results.go
  pkg/service/request_config.go
  pkg/service/request_enrollment.go
  pkg/service/request_queries.go
Labels: observability

#2310 Add Microsoft Defender ATP health tables
  ee/allowedcmd/cmd_darwin.go
  ee/allowedcmd/cmd_linux.go
  ee/disclaim/run_disclaimed_darwin.go
  pkg/osquery/table/platform_tables_darwin.go
  pkg/osquery/table/platform_tables_linux.go
Labels: component:table

#2322 EOL kolide_user_avatars table
  pkg/osquery/table/platform_tables_darwin.go
  pkg/osquery/table/user_avatar_darwin.go
Labels: component:table

#2324 EOL kolide_macos_available_products
  ee/tables/macos_software_update/available_products_table.go
  ee/tables/macos_software_update/sus.h
  ee/tables/macos_software_update/sus.m
  pkg/osquery/table/platform_tables_darwin.go
Labels: component:table

#2325 Do not collect enrollment details until after keys have been generated
  cmd/launcher/launcher.go
Labels: bug-fixes

#2327 TestProc improvements
  pkg/osquery/interactive/interactive_test.go
Labels: tests-docs

#2333 Wait before remediating systray error, and retry remediation if it fails
  ee/desktop/runner/runner.go
Labels: bug-fixes

#2335 Add .exit command to input in TestProc to ensure that process will shut down
  pkg/osquery/interactive/interactive.go
  pkg/osquery/interactive/interactive_test.go
Labels: tests-docs
