Repository kolide/launcher, pull requests merged in 2025-07, with the labels that each got.

#2320 Downgrade more error logs
  ee/desktop/runner/runner.go
  ee/desktop/runner/runner_windows.go
  ee/localserver/krypto-ec-middleware.go
  ee/localserver/server.go
  ee/tables/windowsupdatetable/windowsupdate.go
  pkg/osquery/runtime/runner.go
Labels: observability

#2354 Use runsimple rather than osquery client to populate id fields
  ee/localserver/request-id.go
  ee/localserver/server_test.go
Labels: features-improvements

#2358 ensure crt file cleanup in tests
  pkg/osquery/runtime/osqueryinstance_test.go
Labels: tests-docs

#2307 Include munemo from RegistrationStore in flare upload
  ee/debug/shipper/shipper.go
  ee/debug/shipper/shipper_test.go
Labels: features-improvements

#2368 Fix some flaky tests
  cmd/launcher/desktop_test.go
  pkg/osquery/runtime/osqueryinstance_test.go
Labels: tests-docs

#2371 Only log instance shutdown error if it's not nil or ctx cancel
  pkg/osquery/runtime/runner.go
Labels: observability

#2376 Add feature-flagged performance monitoring to automatically upload flares
  cmd/launcher/launcher.go
  ee/agent/flags/flag_controller.go
  ee/agent/flags/keys/keys.go
  ee/agent/types/flags.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
  ee/debug/performance_monitor.go
  ee/debug/performance_monitor_test.go
Labels: observability

#2377 Group all logs about desktop process startup failures; make logs and errors more verbose
  cmd/launcher/desktop.go
  ee/desktop/runner/runner.go
  ee/desktop/runner/runner_test.go
  ee/desktop/user/server/server.go
Labels: observability

#2380 Log known unprocessable logs at a lower level than error
  ee/log/parser.go
  ee/log/parser_test.go
Labels: observability

#2385 update goleveldb dependency to v0.0.0-20250731160947-c6b056c282de
  go.mod
  go.sum
Labels: bug-fixes, dependencies
