Repository kolide/launcher, pull requests merged in 2025-02, with the labels that each got.

#2080 fix send buffer (log shipping) out of range panic
  pkg/sendbuffer/sendbuffer.go
  pkg/sendbuffer/sendbuffer_test.go
Labels: bug-fixes

#2088 add tenv linter, fix up os.Setenv offenses in tests
  .golangci.yml
  ee/tables/xfconf/xfconf_test.go
  pkg/launcher/options_test.go
  pkg/make/builder_test.go
Labels: tests-docs

#2103 return proper error for homebrew not found on macos
  ee/allowedcmd/cmd_darwin.go
Labels: bug-fixes

#2106 make uninitialized osquery history informational for doctor output
  ee/debug/checkups/osquery_restarts.go
Labels: bug-fixes

#2111 make sure db reset logs encapsulate change values
  ee/agent/reset.go
Labels: bug-fixes

#2113 osquery history cleanup part 2
  pkg/osquery/runtime/history/history.go
  pkg/osquery/runtime/history/history_test.go
  pkg/osquery/runtime/history/instance.go
  pkg/osquery/runtime/history/instance_test.go
  pkg/osquery/runtime/history/storage.go
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/runtime_test.go
Labels: features-improvements

#2123 Update to newest version of root.json
  ee/tuf/assets/tuf/root.json
  pkg/packaging/assets/tuf/root.json
Labels: component:build&packaging

#2124 Further delay calling cancel after uploading flare
  ee/debug/shipper/shipper.go
Labels: bug-fixes

#2131 Remove usage of soon-to-be-deprecated ubuntu-20.04 runner
  .github/workflows/go.yml
Labels: component:build&packaging

#2128 Move KATC tables to restartable extension manager server
  pkg/osquery/interactive/interactive.go
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/osqueryinstance_windows_test.go
  pkg/osquery/runtime/runner.go
  pkg/osquery/runtime/runtime_test.go
  pkg/osquery/table/table.go
Labels: features-improvements
