Repository kolide/launcher, pull requests merged in 2025-01, with the labels that each got.

#2018 Move lockfile logging to osquery log adapter
  ee/log/osquerylogs/log.go
  ee/log/osquerylogs/log_posix.go
  ee/log/osquerylogs/log_windows.go
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/osqueryinstance_other_test.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/osqueryinstance_windows_test.go
  pkg/osquery/runtime/runtime_helpers.go
  pkg/osquery/runtime/runtime_helpers_windows.go
Labels: features-improvements

#2027 Revert "Switch from CoInitialize to CoInitializeEx"
  ee/watchdog/controller_windows.go
Labels: bug-fixes

#2017 Improvements for osqueryinstance's errgroup
  ee/errgroup/errgroup.go
  ee/errgroup/errgroup_test.go
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/runtime_posix_test.go
  pkg/osquery/runtime/runtime_test.go
Labels: features-improvements

#2044 Shut down instances that fail to launch successfully
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/runner.go
  pkg/osquery/runtime/runtime_test.go
  pkg/service/mock/service.go
Labels: bug-fixes

#2041 Retry osquery instance launch faster when we see the stale lockfile issue
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/runner.go
Labels: features-improvements

#2047 Enforce a timeout when shutting down errgroup
  ee/errgroup/errgroup.go
  ee/errgroup/errgroup_test.go
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/runtime_test.go
Labels: features-improvements

#2053 Print logs when flaky autoupdate test fails
  ee/tuf/autoupdate_test.go
Labels: tests-docs

#2054 [KATC] Support fields with JS Date type for Chrome/Firefox extension databases
  ee/indexeddb/values.go
  ee/katc/deserialize_firefox.go
  ee/katc/test_data/indexeddbs/1985929987lbadutnscehter.sqlite.zip
  ee/katc/test_data/indexeddbs/file__0.indexeddb.leveldb.zip
  ee/katc/test_data/main.js
Labels: bug-fixes

#2063 Set an accelerated distributed_interval in the osquery config for the osquery instance startup period
  pkg/osquery/extension.go
  pkg/osquery/extension_test.go
Labels: features-improvements

#2065 Speed up launcher startup and collect more data about slow parts of startup
  cmd/launcher/launcher.go
  ee/agent/storage/bbolt/keyvalue_store_bbolt.go
  ee/agent/storage/bbolt/stores_bbolt.go
  ee/agent/storage/ci/keyvalue_store_ci.go
  ee/agent/storage/ci/keyvalue_store_test.go
  ee/agent/storage/ci/stores_ci.go
  ee/tuf/util.go
  ee/tuf/util_darwin.go
  ee/tuf/util_linux.go
  ee/tuf/util_test.go
  ee/tuf/util_windows.go
  pkg/osquery/extension_test.go
Labels: features-improvements

#2067 Reuse startup settings writer for osquery extension instead of creating a new one for each new config
  cmd/launcher/launcher.go
  pkg/osquery/extension.go
  pkg/osquery/extension_test.go
  pkg/osquery/log_publication_state_test.go
  pkg/osquery/mocks/settings_store_writer.go
  pkg/osquery/runtime/osqueryinstance.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/osqueryinstance_windows_test.go
  pkg/osquery/runtime/runner.go
  pkg/osquery/runtime/runtime_posix_test.go
  pkg/osquery/runtime/runtime_test.go
Labels: bug-fixes

#2015 test cleanup improvements
  pkg/osquery/runsimple/osqueryrunner_test.go
Labels: tests-docs

#2078 Allow a maximum of five ongoing queries per table
  ee/tables/tablewrapper/tablewrapper.go
  ee/tables/tablewrapper/tablewrapper_test.go
Labels: features-improvements
