Repository kolide/launcher, pull requests merged in 2025-04, with the labels that each got.

#2188 [KATC] Support plain leveldb databases
  ee/indexeddb/indexeddb.go
  ee/katc/config.go
  ee/katc/config_test.go
  ee/katc/indexeddb_leveldb.go
  ee/katc/indexeddb_leveldb_test.go
  ee/katc/leveldb.go
  ee/katc/table_test.go
Labels: features-improvements

#2195 [KATC] Add row transform step to decode hex-encoded strings
  ee/katc/config.go
  ee/katc/config_test.go
  ee/katc/hex.go
  ee/katc/hex_test.go
Labels: features-improvements

#2193 Remove deprecated MacOS keys from `socketfilterfw` table
  pkg/osquery/table/platform_tables_darwin.go
Labels: component:table

#1722 package-builder: add podman support via --container_tool
  cmd/package-builder/package-builder.go
  pkg/packagekit/package.go
  pkg/packagekit/package_fpm.go
  pkg/packaging/packaging.go
Labels: component:build&packaging

#2200 [KATC] hexDecode should strip out null chars
  ee/katc/hex.go
Labels: bug-fixes

#2199 [KATC] If sqlite db cannot be queried, continue to query other dbs
  ee/katc/sqlite.go
Labels: component:table

#2201 Maybe improve recent flakiness in TestProc
  pkg/osquery/interactive/interactive.go
  pkg/osquery/interactive/interactive_test.go
Labels: tests-docs

#2202 Try running TestProc subtests in sequence rather than in parallel, to avoid pollution
  pkg/osquery/interactive/interactive_test.go
Labels: tests-docs

#2194 Allow for compacting backup dbs
  cmd/launcher/run_compactdb.go
  pkg/launcher/options.go
  pkg/launcher/options_test.go
Labels: features-improvements

#2222 Add first metrics to our telemetry
  ee/observability/exporter/exporter.go
  ee/observability/meter.go
  ee/observability/meter_test.go
  ee/performance/stats.go
  go.mod
  go.sum
  pkg/osquery/runtime/runner.go
Labels: features-improvements

#2223 Export metrics to ingest server
  ee/observability/exporter/exporter.go
  ee/observability/exporter/exporter_test.go
  ee/observability/meter.go
  ee/observability/meter_test.go
  go.mod
  go.sum
Labels: features-improvements

#2229 Add rungroup actor to periodically cache results of querying Windows Update Agent API
  cmd/launcher/launcher.go
  ee/agent/knapsack/knapsack.go
  ee/agent/storage/bbolt/stores_bbolt.go
  ee/agent/storage/ci/stores_ci.go
  ee/agent/storage/stores.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
  ee/agent/types/stores.go
  ee/tables/windowsupdatetable/cache_other.go
  ee/tables/windowsupdatetable/cache_test.go
  ee/tables/windowsupdatetable/cache_windows.go
  ee/tables/windowsupdatetable/windowsupdate.go
Labels: features-improvements

#2231 Add flag `use_cached_data_for_scheduled_queries`, and rewrite osquery config accordingly when set
  ee/agent/flags/flag_controller.go
  ee/agent/flags/keys/keys.go
  ee/agent/types/flags.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
  pkg/osquery/extension.go
  pkg/osquery/extension_test.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/runtime_posix_test.go
  pkg/osquery/runtime/runtime_test.go
Labels: features-improvements

#2233 Add telemetry attribute launcher.goos
  ee/observability/exporter/exporter_test.go
  ee/observability/exporter/initial_trace_buffer.go
Labels: features-improvements

#2234 Immediately cache data rather than waiting 1 hour
  ee/tables/windowsupdatetable/cache_windows.go
Labels: features-improvements

#2235 Throw more time at query-windowsupdates
  ee/tables/windowsupdatetable/cache_windows.go
Labels: features-improvements
