Repository kolide/launcher, pull requests merged in 2025-03, with the labels that each got.

#2135 [IndexedDB/KATC] Implement JS map and JS set deserialization for chrome and firefox
  ee/indexeddb/values.go
  ee/katc/deserialize_firefox.go
  ee/katc/test_data/indexeddbs/1985929987lbadutnscehter.sqlite.zip
  ee/katc/test_data/indexeddbs/file__0.indexeddb.leveldb.zip
  ee/katc/test_data/main.js
Labels: features-improvements

#2138 Explicitly initialize startup settings store in test
  pkg/osquery/interactive/interactive_test.go
Labels: tests-docs

#2136 add system startup trigger to watchdog
  ee/watchdog/controller_windows.go
Labels: features-improvements

#2144 [IndexedDB/KATC] Implement or partially implement parsing for BigInts, Strings, arrays containing data other than strings and objects, and others
  ee/indexeddb/values.go
  ee/katc/deserialize_firefox.go
  ee/katc/test_data/README.md
  ee/katc/test_data/indexeddbs/1985929987lbadutnscehter.sqlite.zip
  ee/katc/test_data/indexeddbs/file__0.indexeddb.leveldb.zip
  ee/katc/test_data/main.js
Labels: features-improvements

#2145 Wait up to 20 seconds for runLauncher shutdown on service shutdown request
  cmd/launcher/svc_windows.go
Labels: bug-fixes

#2148 [IndexedDB/KATC] TypedArrays and ArrayBuffers
  ee/indexeddb/values.go
  ee/katc/deserialize_firefox.go
  ee/katc/test_data/indexeddbs/1985929987lbadutnscehter.sqlite.zip
  ee/katc/test_data/indexeddbs/file__0.indexeddb.leveldb.zip
  ee/katc/test_data/main.js
Labels: features-improvements

#2150 Log CheckExecutable thoroughly
  ee/tuf/library_lookup.go
  ee/tuf/library_manager.go
  ee/tuf/library_manager_test.go
  ee/tuf/util.go
  ee/tuf/util_test.go
Labels: features-improvements

#2151 Do not suppress errors when running CheckExecutable
  ee/tuf/ci/valid_executable.go
  ee/tuf/util.go
  ee/tuf/util_test.go
Labels: bug-fixes

#2152 Build for linux in ubuntu 20.04 container
  .github/workflows/go.yml
Labels: component:build&packaging

#2142 Root.json generator
  .gitignore
  Makefile
  ee/tuf/assets/tuf/root.json
  ee/tuf/gen.go
  ee/tuf/generator/assets/initial_root.json
  ee/tuf/generator/generator.go
  pkg/packaging/assets/tuf/root.json
Labels: component:build&packaging

#2154 checking in root.json for packaging
  .gitignore
  pkg/packaging/assets/tuf/root.json
Labels: component:build&packaging

#2153 Requests to the control server should have timeouts set
  ee/control/client_http.go
Labels: bug-fixes

#2157 Allow for manipulating osquery's effective distributed_interval within 5 seconds
  pkg/osquery/extension.go
  pkg/osquery/extension_test.go
  pkg/service/request_queries.go
Labels: features-improvements

#2159 Add Exec Test job for containers
  .github/workflows/go.yml
Labels: component:build&packaging

#2160 Add two new flags controlling acceleration
  ee/agent/flags/flag_controller.go
  ee/agent/flags/keys/keys.go
  ee/agent/types/flags.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
Labels: features-improvements

#2163 Support target parsing for non-default arches
  pkg/packaging/target.go
  pkg/packaging/target_test.go
Labels: component:build&packaging

#2161 Allow dt4a endpoints to accelerate control + osquery request intervals
  ee/agent/flags/flag_controller.go
  ee/agent/flags/flag_controller_test.go
  ee/agent/types/flags.go
  ee/agent/types/mocks/flags.go
  ee/agent/types/mocks/knapsack.go
  ee/localserver/dt4a.go
  ee/localserver/dt4a_auth_middleware.go
  ee/localserver/dt4a_auth_middleware_test.go
  ee/localserver/dt4a_test.go
  ee/localserver/server.go
  pkg/osquery/extension.go
  pkg/osquery/extension_test.go
  pkg/osquery/runtime/osqueryinstance_test.go
  pkg/osquery/runtime/runtime_posix_test.go
  pkg/osquery/runtime/runtime_test.go
Labels: features-improvements

#2165 KVStore.Get should return nil, not error, when no results are found
  ee/agent/storage/sqlite/keyvalue_store_sqlite.go
Labels: bug-fixes

#2168 make deps + build default make
  Makefile
Labels: component:build&packaging

#2171 Check that ATC config exists before making a plugin out of it
  pkg/osquery/interactive/interactive.go
Labels: bug-fixes

#2174 Add logs to indicate when launcher is checking for updates
  ee/tuf/autoupdate.go
  ee/tuf/autoupdate_test.go
  ee/tuf/library_manager.go
Labels: features-improvements

#2177 Remove old tracing library from launcher
  go.mod
  go.sum
  pkg/contexts/ctxlog/ctxlog.go
  pkg/contexts/ctxlog/ctxlog_test.go
  pkg/make/builder.go
  pkg/packagekit/authenticode/authenticode_windows.go
  pkg/packagekit/package_fpm.go
  pkg/packagekit/package_pkg.go
  pkg/packagekit/package_wix.go
  pkg/packagekit/render_init.go
  pkg/packagekit/render_launchd.go
  pkg/packagekit/render_systemd.go
  pkg/packagekit/render_upstart.go
  pkg/packaging/fetch.go
  pkg/packaging/packaging.go
Labels: features-improvements

#2178 Switch from default freelist type to more performant option
  cmd/launcher/launcher.go
Labels: features-improvements

#2185 Add `launcher query-windowsupdates` subcommand to avoid memory leak temporarily
  cmd/launcher/main.go
  cmd/launcher/query_windowsupdates_other.go
  cmd/launcher/query_windowsupdates_windows.go
  ee/tables/windowsupdatetable/windowsupdate.go
  ee/tables/windowsupdatetable/windowsupdate_test.go
Labels: bug-fixes
